export const GET_CART = 'GET_CART';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART';
export const ADD_PRODUCT_CART_SUCCESS = 'ADD_PRODUCT_CART_SUCCESS';
export const REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART';
export const REMOVE_PRODUCT_CART_SUCCESS = 'REMOVE_PRODUCT_CART_SUCCESS';
export const EDIT_PRODUCT_CART = 'EDIT_PRODUCT_CART';
export const EDIT_PRODUCT_CART_SUCCESS = 'EDIT_PRODUCT_CART_SUCCESS';